### ISSUE TITLE
Just make .gitignore ignore **/.idea 

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/tbdex-android-example#7]
Hey @michaelneale - 

```
$> git add -Av
add '.idea/.gitignore'
add '.idea/.name'
add '.idea/codeStyles/Project.xml'
add '.idea/codeStyles/codeStyleConfig.xml'
add '.idea/compiler.xml'
add '.idea/deploymentTargetDropDown.xml'
add '.idea/gradle.xml'
add '.idea/kotlinc.xml'
add '.idea/migrations.xml'
add '.idea/misc.xml'
add '.idea/vcs.xml'
```

Shall we just have `.gitignore` ignore the whole `./.idea` directory? Or do you know something I don't where it's best to commit some common IDE configs? Saw your current config is fine-grained in what it'll ignore.

**Comment by michaelneale** [comment]
the one I have is what android studio made - so presumably that is what it uses? just defaults!
